### ISSUE TITLE
Custom JSON serializer not being used for bulk operations

### ISSUE THREAD

**Issue by sushi2all** [arangodb/python-arango#240] opened 2023-01-09 10:04 UTC
Hello, thanks so much for your work. I'm loving the library and relying heavily on it for a new enterprise web app.

I'm setting up import procedures but had troubles because the custom serializer is not being used with the `import_bulk` and `insert_many` methods of the collection (and possibly in other bulk operations).

When inserting a single document the custom serializer is working fine.

Can this be implemented?

**Comment by apetenchea** [comment] 2024-05-20 18:45
Hi @sushi2all 

Could you please be a bit more explicit? What do you mean by "the custom serializer is not being used"?

It is being used by all methods that send a request, including the ones you mentioned: `insert_many` and `import_bulk`. Could you please double-check that? Maybe the problem got fixed in the meantime.

I tested it locally, with the last release (commit https://github.com/arangodb/python-arango/blob/99f5d9bf9c06f6845957df4604181ac067b14feb, corresponding to 7.9.1).
Data is always [normalized](https://github.com/arangodb/python-arango/blob/99f5d9bf9c06f6845957df4604181ac067b14feb/arango/connection.py#L188) while processing [every request](https://github.com/arangodb/python-arango/blob/99f5d9bf9c06f6845957df4604181ac067b14feb/arango/connection.py#L122). I hope I'm not being overly confusing here by pointing at the code (that's not the idea), I'm just trying to check whether I got your question right.

Please let me know whether the problem is still there, otherwise I think we can close the issue.

**Comment by apetenchea** [comment] 2024-05-25 15:52
Closing as completed. Feel free to open another one in case you still experience any issues.

**Closed by apetenchea** 2024-05-25 15:52 UTC
Labels: enhancement
